### ISSUE TITLE
Set up basic build and dependencies with skeletal binary messaging code

### ISSUE THREAD

**Issue by kdowney-lot49** [iggy-rs/iggy-cpp-client#6]
Mirror messages as defined in:

- https://github.com/iggy-rs/iggy-dotnet-client/blob/master/Iggy_SDK/Contracts/Tcp/TcpContracts.cs
- https://docs.iggy.rs/specification/binary

**Comment by kdowney-lot49** [comment]
Might be a good idea to start with GetStats:

- https://github.com/iggy-rs/iggy/blob/bd4de53474fd2fa79e3d700a967711c25397f5ca/iggy/src/models/stats.rs
- https://github.com/iggy-rs/iggy/blob/bd4de53474fd2fa79e3d700a967711c25397f5ca/server/src/streaming/systems/stats.rs

**Comment by spetz** [comment]
Please keep in mind that most of the actions (including `stats`), do require the connected apps to be authenticated - it'd be probably even easier to start with something as simple as `ping`, and then move onto the `login_user` (using the default `iggy/iggy` root credentials), which will establish the authenticated session and allow for further calls to the remaining methods.

**Comment by hubcio** [comment]
Indeed - IMHO first action should be login/ping

**Comment by kdowney-lot49** [comment]
Noted, thanks!

**Comment by kdowney-lot49** [comment]
This is turning into a saga, going to break it into smaller pieces so there's no long-running branch.
